### ISSUE TITLE
No way to unselect a message

### ISSUE THREAD

**Issue by Arcanemagus** [facebook-atom/atom-ide-ui#82]
### Description
If you _ever_ click a message, you are permanently stuck with a selected message in your panel until you remove all messages or reload Atom.

### Expected Behavior
Clicking elsewhere in the editor (out of the range of the `diagnostic`), or in a blank area of the panel should deselect the message.

### Actual Behavior
Once a message is selected you can only deselect it by selecting another message.

### Versions
* Atom: v1.22.0-beta0
* Client OS: Windows 10 x64
* atom-ide-ui: v0.5.0

**Comment by matthewwithanm** [comment]
This should be fixed in 0.5.2 😊

**Comment by Arcanemagus** [comment]
Confirmed, thanks!

**Comment by Arcanemagus** [comment]
Looks like this is a problem again starting with `atom-ide-ui@0.5.4`. Instead of deselecting the message it is highlighted instead. `atom-ide-ui@0.6.0` has the same behavior.

**Comment by Arcanemagus** [comment]
@matthewwithanm This is still a problem in v0.7.0, should I file a new issue about it or should this just be reopened?
